name: rehan_prf
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source San
      fonts:
        - asset: fonts/SourceSerif4-Italic-VariableFont_opsz,wght.ttf
    - family: Source Sans
      fonts:
        - asset: fonts/SourceSerif4-VariableFont_opsz,wght.ttf

    - family: SourceSerif
      fonts:
        - asset: fonts/SourceSerif4-Regular.ttf